apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: jumpbox.tanzu.vmware.com
  namespace: jumpbox
spec:
  refName: jumpbox.tanzu.vmware.com
  version: v1.0.1
  releaseNotes: "Repackagin with new tooling from the Tanzu Framework team"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: # Get this value by pushing to your OCI Registry
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
