#@data/values
---
repositories:
  management:
    version: null
    sha256: latest
    name: simple-repo
    domain: example.com
    registry: registry

    packageSpec:
      syncPeriod: 5m
      deploy:
        kappWaitTimeout: 5m
        kubeAPIQPS: 20
        kubeAPIBurst: 30

    packages:
      - name: jumpbox
        displayName: jumpbox
        #! Relative path to package bundle
        path: packages/jumpbox
        domain: jumpbox.tanzu.vmware.com
        version: latest
        #! Gets replaced with imgpkg sha256 at build, this should be name:version
        sha256: "jumpbox-plugin:latest"
